server:
  port: 8080
  servlet:
    context-path: /

spring:
#  flyway:
#    locations: classpath:/db/migration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:java;MODE=PostgreSQL
    username: postgres
    password: