server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shop
      username: postgres
      password: admin
#    url: jdbc:h2:mem:test
#    username: root
#    password: root
#    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jackson:
    serialization:
      indent_output: true